//! NGAP Information Element ID lookup table.
//!
//! 3GPP TS 38.413, Section 9.4.5 —
//! <https://www.3gpp.org/ftp/Specs/archive/38_series/38.413/>

/// Returns a human-readable name for the given NGAP IE ID.
///
/// 3GPP TS 38.413, Section 9.4.5.
pub fn ie_id_name(id: u16) -> &'static str {
    match id {
        0 => "AllowedNSSAI",
        1 => "AMFName",
        2 => "AMFOverloadResponse",
        3 => "AMFSetID",
        4 => "AMF-TNLAssociationFailedToSetupList",
        5 => "AMF-TNLAssociationSetupList",
        6 => "AMF-TNLAssociationToAddList",
        7 => "AMF-TNLAssociationToRemoveList",
        8 => "AMF-TNLAssociationToUpdateList",
        9 => "AMFTrafficLoadReductionIndication",
        10 => "AMF-UE-NGAP-ID",
        11 => "AssistanceDataForPaging",
        12 => "BroadcastCancelledAreaList",
        13 => "BroadcastCompletedAreaList",
        14 => "CancelAllWarningMessages",
        15 => "Cause",
        16 => "CellIDListForRestart",
        17 => "ConcurrentWarningMessageInd",
        18 => "CoreNetworkAssistanceInformation",
        19 => "CriticalityDiagnostics",
        20 => "DataCodingScheme",
        21 => "DefaultPagingDRX",
        22 => "DirectForwardingPathAvailability",
        23 => "EmergencyAreaIDListForRestart",
        24 => "EmergencyFallbackIndicator",
        25 => "EUTRA-CGI",
        26 => "FiveG-S-TMSI",
        27 => "GlobalRANNodeID",
        28 => "GUAMI",
        29 => "HandoverType",
        30 => "IMSVoiceSupportIndicator",
        31 => "IndexToRFSP",
        32 => "InfoOnRecommendedCellsAndRANNodesForPaging",
        33 => "LocationReportingRequestType",
        34 => "MaskedIMEISV",
        35 => "MessageIdentifier",
        36 => "MobilityRestrictionList",
        37 => "NASC",
        38 => "NAS-PDU",
        39 => "NASSecurityParametersFromNGRAN",
        40 => "NewAMF-UE-NGAP-ID",
        41 => "NewSecurityContextInd",
        42 => "NGAP-Message",
        43 => "NGRA-CGI",
        44 => "NGRANTraceID",
        45 => "NR-CGI",
        46 => "NRPPa-PDU",
        47 => "NumberOfBroadcastsRequested",
        48 => "OldAMF",
        49 => "OverloadStartNSSAIList",
        50 => "PagingDRX",
        51 => "PagingOrigin",
        52 => "PagingPriority",
        53 => "PDUSessionResourceAdmittedList",
        54 => "PDUSessionResourceFailedToModifyListModRes",
        55 => "PDUSessionResourceFailedToSetupListCxtRes",
        56 => "PDUSessionResourceFailedToSetupListHOAck",
        57 => "PDUSessionResourceFailedToSetupListPSReq",
        58 => "PDUSessionResourceFailedToSetupListSURes",
        59 => "PDUSessionResourceHandoverList",
        60 => "PDUSessionResourceListCxtRelCpl",
        61 => "PDUSessionResourceListHORqd",
        62 => "PDUSessionResourceModifyListModCfm",
        63 => "PDUSessionResourceModifyListModInd",
        64 => "PDUSessionResourceModifyListModReq",
        65 => "PDUSessionResourceModifyListModRes",
        66 => "PDUSessionResourceNotifyList",
        67 => "PDUSessionResourceReleasedListNot",
        68 => "PDUSessionResourceReleasedListPSAck",
        69 => "PDUSessionResourceReleasedListPSFail",
        70 => "PDUSessionResourceReleasedListRelRes",
        71 => "PDUSessionResourceSetupListCxtReq",
        72 => "PDUSessionResourceSetupListCxtRes",
        73 => "PDUSessionResourceSetupListHOReq",
        74 => "PDUSessionResourceSetupListSUReq",
        75 => "PDUSessionResourceSetupListSURes",
        76 => "PDUSessionResourceToBeSwitchedDLList",
        77 => "PDUSessionResourceSwitchedList",
        78 => "PDUSessionResourceToReleaseListHOCmd",
        79 => "PDUSessionResourceToReleaseListRelCmd",
        80 => "PLMNSupportList",
        81 => "PWSFailedCellIDList",
        82 => "RANNodeName",
        83 => "RANPagingPriority",
        84 => "RANStatusTransfer-TransparentContainer",
        85 => "RAN-UE-NGAP-ID",
        86 => "RelativeAMFCapacity",
        87 => "RepetitionPeriod",
        88 => "ResetType",
        89 => "RoutingID",
        90 => "RRCEstablishmentCause",
        91 => "RRCInactiveTransitionReportRequest",
        92 => "RRCState",
        93 => "SecurityContext",
        94 => "SecurityKey",
        95 => "SerialNumber",
        96 => "ServedGUAMIList",
        97 => "SliceSupportList",
        98 => "SONConfigurationTransferDL",
        99 => "SONConfigurationTransferUL",
        100 => "SourceAMF-UE-NGAP-ID",
        101 => "SourceToTarget-TransparentContainer",
        102 => "SupportedTAList",
        103 => "TAIListForPaging",
        104 => "TAIListForRestart",
        105 => "TargetID",
        106 => "TargetToSource-TransparentContainer",
        107 => "TimeToWait",
        108 => "TraceActivation",
        109 => "TraceCollectionEntityIPAddress",
        110 => "UEAggregateMaximumBitRate",
        111 => "UE-associatedLogicalNG-connectionList",
        112 => "UEContextRequest",
        114 => "UE-NGAP-IDs",
        115 => "UEPagingIdentity",
        116 => "UEPresenceInAreaOfInterestList",
        117 => "UERadioCapability",
        118 => "UERadioCapabilityForPaging",
        119 => "UESecurityCapabilities",
        120 => "UnavailableGUAMIList",
        121 => "UserLocationInformation",
        122 => "WarningAreaList",
        123 => "WarningMessageContents",
        124 => "WarningSecurityInfo",
        125 => "WarningType",
        126 => "AdditionalUL-NGU-UP-TNLInformation",
        127 => "DataForwardingNotPossible",
        128 => "DL-NGU-UP-TNLInformation",
        129 => "NetworkInstance",
        130 => "PDUSessionAggregateMaximumBitRate",
        131 => "PDUSessionResourceFailedToModifyListModCfm",
        132 => "PDUSessionResourceFailedToSetupListCxtFail",
        133 => "PDUSessionResourceListCxtRelReq",
        134 => "PDUSessionType",
        135 => "QosFlowAddOrModifyRequestList",
        136 => "QosFlowSetupRequestList",
        137 => "QosFlowToReleaseList",
        138 => "SecurityIndication",
        139 => "UL-NGU-UP-TNLInformation",
        140 => "UL-NGU-UP-TNLModifyList",
        141 => "WarningAreaCoordinates",
        142 => "PDUSessionResourceSecondaryRATUsageList",
        143 => "HandoverFlag",
        144 => "SecondaryRATUsageInformation",
        145 => "PDUSessionResourceReleaseResponseTransfer",
        146 => "RedirectionVoiceFallback",
        147 => "UERetentionInformation",
        148 => "S-NSSAI",
        149 => "PSCellInformation",
        150 => "LastEUTRANPLMNIdentity",
        151 => "MaximumIntegrityProtectedDataRateDL",
        152 => "AdditionalDLForwardingUPTNLInformation",
        153 => "AdditionalDLUPTNLInformationForHOList",
        154 => "AdditionalNGU-UP-TNLInformation",
        155 => "AdditionalDLQosFlowPerTNLInformation",
        156 => "SecurityResult",
        157 => "ENDCSONConfigurationTransferDL",
        158 => "ENDCSONConfigurationTransferUL",
        _ => "Unknown",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_ie_ids() {
        assert_eq!(ie_id_name(10), "AMF-UE-NGAP-ID");
        assert_eq!(ie_id_name(85), "RAN-UE-NGAP-ID");
        assert_eq!(ie_id_name(38), "NAS-PDU");
        assert_eq!(ie_id_name(15), "Cause");
        assert_eq!(ie_id_name(19), "CriticalityDiagnostics");
        assert_eq!(ie_id_name(86), "RelativeAMFCapacity");
        assert_eq!(ie_id_name(148), "S-NSSAI");
    }

    #[test]
    fn unknown_ie_id() {
        assert_eq!(ie_id_name(9999), "Unknown");
    }
}
