//! E1AP Protocol IE ID lookup table.
//!
//! 3GPP TS 37.483 v19.4.0, Section 9.4.7 (Constant definitions) —
//! <https://www.3gpp.org/ftp/Specs/archive/37_series/37.483/>

/// Returns a human-readable name for the given E1AP IE ID.
///
/// The names are the `id-` constants of 3GPP TS 37.483, Section 9.4.7,
/// without the `id-` prefix. Unassigned values return `"Unknown"`.
pub fn ie_id_name(value: u16) -> &'static str {
    match value {
        0 => "Cause",
        1 => "CriticalityDiagnostics",
        2 => "gNB-CU-CP-UE-E1AP-ID",
        3 => "gNB-CU-UP-UE-E1AP-ID",
        4 => "ResetType",
        5 => "UE-associatedLogicalE1-ConnectionItem",
        6 => "UE-associatedLogicalE1-ConnectionListResAck",
        7 => "gNB-CU-UP-ID",
        8 => "gNB-CU-UP-Name",
        9 => "gNB-CU-CP-Name",
        10 => "CNSupport",
        11 => "SupportedPLMNs",
        12 => "TimeToWait",
        13 => "SecurityInformation",
        14 => "UEDLAggregateMaximumBitRate",
        15 => "System-BearerContextSetupRequest",
        16 => "System-BearerContextSetupResponse",
        17 => "BearerContextStatusChange",
        18 => "System-BearerContextModificationRequest",
        19 => "System-BearerContextModificationResponse",
        20 => "System-BearerContextModificationConfirm",
        21 => "System-BearerContextModificationRequired",
        22 => "DRB-Status-List",
        23 => "ActivityNotificationLevel",
        24 => "ActivityInformation",
        25 => "Data-Usage-Report-List",
        26 => "New-UL-TNL-Information-Required",
        27 => "GNB-CU-CP-TNLA-To-Add-List",
        28 => "GNB-CU-CP-TNLA-To-Remove-List",
        29 => "GNB-CU-CP-TNLA-To-Update-List",
        30 => "GNB-CU-CP-TNLA-Setup-List",
        31 => "GNB-CU-CP-TNLA-Failed-To-Setup-List",
        32 => "DRB-To-Setup-List-EUTRAN",
        33 => "DRB-To-Modify-List-EUTRAN",
        34 => "DRB-To-Remove-List-EUTRAN",
        35 => "DRB-Required-To-Modify-List-EUTRAN",
        36 => "DRB-Required-To-Remove-List-EUTRAN",
        37 => "DRB-Setup-List-EUTRAN",
        38 => "DRB-Failed-List-EUTRAN",
        39 => "DRB-Modified-List-EUTRAN",
        40 => "DRB-Failed-To-Modify-List-EUTRAN",
        41 => "DRB-Confirm-Modified-List-EUTRAN",
        42 => "PDU-Session-Resource-To-Setup-List",
        43 => "PDU-Session-Resource-To-Modify-List",
        44 => "PDU-Session-Resource-To-Remove-List",
        45 => "PDU-Session-Resource-Required-To-Modify-List",
        46 => "PDU-Session-Resource-Setup-List",
        47 => "PDU-Session-Resource-Failed-List",
        48 => "PDU-Session-Resource-Modified-List",
        49 => "PDU-Session-Resource-Failed-To-Modify-List",
        50 => "PDU-Session-Resource-Confirm-Modified-List",
        51 => "DRB-To-Setup-Mod-List-EUTRAN",
        52 => "DRB-Setup-Mod-List-EUTRAN",
        53 => "DRB-Failed-Mod-List-EUTRAN",
        54 => "PDU-Session-Resource-Setup-Mod-List",
        55 => "PDU-Session-Resource-Failed-Mod-List",
        56 => "PDU-Session-Resource-To-Setup-Mod-List",
        57 => "TransactionID",
        58 => "Serving-PLMN",
        59 => "UE-Inactivity-Timer",
        60 => "System-GNB-CU-UP-CounterCheckRequest",
        61 => "DRBs-Subject-To-Counter-Check-List-EUTRAN",
        62 => "DRBs-Subject-To-Counter-Check-List-NG-RAN",
        63 => "PPI",
        64 => "gNB-CU-UP-Capacity",
        65 => "GNB-CU-UP-OverloadInformation",
        66 => "UEDLMaximumIntegrityProtectedDataRate",
        67 => "PDU-Session-To-Notify-List",
        68 => "PDU-Session-Resource-Data-Usage-List",
        69 => "SNSSAI",
        70 => "DataDiscardRequired",
        71 => "OldQoSFlowMap-ULendmarkerexpected",
        72 => "DRB-QoS",
        73 => "GNB-CU-UP-TNLA-To-Remove-List",
        74 => "endpoint-IP-Address-and-Port",
        75 => "TNLAssociationTransportLayerAddressgNBCUUP",
        76 => "RANUEID",
        77 => "GNB-DU-ID",
        78 => "CommonNetworkInstance",
        79 => "NetworkInstance",
        80 => "QoSFlowMappingIndication",
        81 => "TraceActivation",
        82 => "TraceID",
        83 => "SubscriberProfileIDforRFP",
        84 => "AdditionalRRMPriorityIndex",
        85 => "RetainabilityMeasurementsInfo",
        86 => "Transport-Layer-Address-Info",
        87 => "QoSMonitoringRequest",
        88 => "PDCP-StatusReportIndication",
        89 => "gNB-CU-CP-Measurement-ID",
        90 => "gNB-CU-UP-Measurement-ID",
        91 => "RegistrationRequest",
        92 => "ReportCharacteristics",
        93 => "ReportingPeriodicity",
        94 => "TNL-AvailableCapacityIndicator",
        95 => "HW-CapacityIndicator",
        96 => "RedundantCommonNetworkInstance",
        97 => "redundant-nG-UL-UP-TNL-Information",
        98 => "redundant-nG-DL-UP-TNL-Information",
        99 => "RedundantQosFlowIndicator",
        100 => "TSCTrafficCharacteristics",
        101 => "CNPacketDelayBudgetDownlink",
        102 => "CNPacketDelayBudgetUplink",
        103 => "ExtendedPacketDelayBudget",
        104 => "AdditionalPDCPduplicationInformation",
        105 => "RedundantPDUSessionInformation",
        106 => "RedundantPDUSessionInformation-used",
        107 => "QoS-Mapping-Information",
        108 => "DLUPTNLAddressToUpdateList",
        109 => "ULUPTNLAddressToUpdateList",
        110 => "NPNSupportInfo",
        111 => "NPNContextInfo",
        112 => "MDTConfiguration",
        113 => "ManagementBasedMDTPLMNList",
        114 => "TraceCollectionEntityIPAddress",
        115 => "PrivacyIndicator",
        116 => "TraceCollectionEntityURI",
        117 => "URIaddress",
        118 => "EHC-Parameters",
        119 => "DRBs-Subject-To-Early-Forwarding-List",
        120 => "DAPSRequestInfo",
        121 => "CHOInitiation",
        122 => "EarlyForwardingCOUNTReq",
        123 => "EarlyForwardingCOUNTInfo",
        124 => "AlternativeQoSParaSetList",
        125 => "ExtendedSliceSupportList",
        126 => "MCG-OfferedGBRQoSFlowInfo",
        127 => "Number-of-tunnels",
        128 => "DRB-Measurement-Results-Information-List",
        129 => "Extended-GNB-CU-CP-Name",
        130 => "Extended-GNB-CU-UP-Name",
        131 => "DataForwardingtoE-UTRANInformationList",
        132 => "QosMonitoringReportingFrequency",
        133 => "QoSMonitoringDisabled",
        134 => "AdditionalHandoverInfo",
        135 => "Extended-NR-CGI-Support-List",
        136 => "DataForwardingtoNG-RANQoSFlowInformationList",
        137 => "MaxCIDEHCDL",
        138 => "ignoreMappingRuleIndication",
        139 => "DirectForwardingPathAvailability",
        140 => "EarlyDataForwardingIndicator",
        141 => "QoSFlowsDRBRemapping",
        142 => "DataForwardingSourceIPAddress",
        143 => "SecurityIndicationModify",
        144 => "IAB-Donor-CU-UPPSKInfo",
        145 => "ECGI-Support-List",
        146 => "MDTPollutedMeasurementIndicator",
        147 => "M4ReportAmount",
        148 => "M6ReportAmount",
        149 => "M7ReportAmount",
        150 => "UESliceMaximumBitRateList",
        151 => "PDUSession-PairID",
        152 => "SurvivalTime",
        153 => "UDC-Parameters",
        154 => "SCGActivationStatus",
        155 => "GNB-CU-CP-MBS-E1AP-ID",
        156 => "GNB-CU-UP-MBS-E1AP-ID",
        157 => "GlobalMBSSessionID",
        158 => "BCBearerContextToSetup",
        159 => "BCBearerContextToSetupResponse",
        160 => "BCBearerContextToModify",
        161 => "BCBearerContextToModifyResponse",
        162 => "BCBearerContextToModifyRequired",
        163 => "BCBearerContextToModifyConfirm",
        164 => "MCBearerContextToSetup",
        165 => "MCBearerContextToSetupResponse",
        166 => "MCBearerContextToModify",
        167 => "MCBearerContextToModifyResponse",
        168 => "MCBearerContextToModifyRequired",
        169 => "MCBearerContextToModifyConfirm",
        170 => "MBSMulticastF1UContextDescriptor",
        171 => "gNB-CU-UP-MBS-Support-Info",
        172 => "SecurityIndication",
        173 => "SecurityResult",
        174 => "SDTContinueROHC",
        175 => "SDTindicatorSetup",
        176 => "SDTindicatorMod",
        177 => "DiscardTimerExtended",
        178 => "ManagementBasedMDTPLMNModificationList",
        179 => "MCForwardingResourceRequest",
        180 => "MCForwardingResourceIndication",
        181 => "MCForwardingResourceResponse",
        182 => "MCForwardingResourceRelease",
        183 => "MCForwardingResourceReleaseIndication",
        184 => "PDCP-COUNT-Reset",
        185 => "MBSSessionAssociatedInfoNonSupportToSupport",
        186 => "VersionID",
        187 => "InactivityInformationRequest",
        188 => "UEInactivityInformation",
        189 => "MBSAreaSessionID",
        190 => "Secondary-PDU-Session-Data-Forwarding-Information",
        191 => "MBSSessionResourceNotification",
        192 => "MCBearerContextInactivityTimer",
        193 => "MCBearerContextStatusChange",
        194 => "MT-SDT-Information",
        195 => "MT-SDT-Information-Request",
        196 => "SDT-data-size-threshold",
        197 => "SDT-data-size-threshold-Crossed",
        198 => "SpecialTriggeringPurpose",
        199 => "AssociatedSessionID",
        200 => "MBS-ServiceArea",
        201 => "PDUSetQoSParameters",
        202 => "N6JitterInformation",
        203 => "ECNMarkingorCongestionInformationReportingRequest",
        204 => "ECNMarkingorCongestionInformationReportingStatus",
        205 => "PDUSetbasedHandlingIndicator",
        206 => "IndirectPathIndication",
        207 => "F1UTunnelNotEstablished",
        208 => "F1U-TNL-InfoToAdd-List",
        209 => "F1U-TNL-InfoAdded-List",
        210 => "F1U-TNL-InfoToAddOrModify-List",
        211 => "F1U-TNL-InfoAddedOrModified-List",
        212 => "F1U-TNL-InfoToRelease-List",
        213 => "BroadcastF1U-ContextReferenceE1",
        214 => "PSIbasedDiscardTimer",
        215 => "UserPlaneErrorIndicator",
        216 => "MaximumDataBurstVolume",
        217 => "BCBearerContextNGU-TNLInfoatNGRAN-Request",
        218 => "PDCPSNGapReport",
        219 => "UserPlaneFailureIndication",
        220 => "InactivityMonitoring",
        221 => "MCBearerContextNGUTnlInfoatNGRANReplaceRequest",
        222 => "LTMInitiation",
        223 => "RegistrationRequestForDataCollection",
        224 => "ReportCharacteristicsForDataCollection",
        225 => "ReportingPeriodicityForDataCollection",
        226 => "UEAssociatedInfoResult-List",
        227 => "DataCollectionID",
        228 => "PduSetDelayBudgetDownlink",
        229 => "PduSetDelayBudgetUplink",
        230 => "PduSetErrorRateDownlink",
        231 => "PduSetErrorRateUplink",
        232 => "MonitoringRequestonAvailableBitrate",
        233 => "MMSID",
        234 => "Remaining-time-based-rLC-retransmission-threshold",
        235 => "Remaining-time-based-rLC-polling-threshold",
        236 => "DL-PDU-Set-Info-Marking-Support-Ind",
        237 => "UEPerformanceCollectionConfiguration",
        238 => "NodeMeasurementInitiationResult-List",
        _ => "Unknown",
    }
}

#[cfg(test)]
mod tests {
    //! # 3GPP TS 37.483 Protocol IE ID Coverage
    //!
    //! | Spec Section | Description                            | Test                |
    //! |--------------|----------------------------------------|---------------------|
    //! | 9.4.7        | Known constants                        | known_values        |
    //! | 9.4.7        | Every assigned value is named          | all_assigned_named  |
    //! | 9.4.7        | Unassigned values                      | unknown_values      |

    use super::*;

    /// Values not assigned to any `id-` constant in TS 37.483 v19.4.0,
    /// Section 9.4.7.
    const UNASSIGNED: &[u16] = &[];

    #[test]
    fn known_values() {
        assert_eq!(ie_id_name(0), "Cause");
        assert_eq!(ie_id_name(119), "DRBs-Subject-To-Early-Forwarding-List");
        assert_eq!(ie_id_name(238), "NodeMeasurementInitiationResult-List");
    }

    #[test]
    fn all_assigned_named() {
        for value in 0..=238u16 {
            let named = ie_id_name(value) != "Unknown";
            assert_eq!(named, !UNASSIGNED.contains(&value), "value {value}");
        }
    }

    #[test]
    fn unknown_values() {
        assert_eq!(ie_id_name(239), "Unknown");
        assert_eq!(ie_id_name(u16::MAX), "Unknown");
    }
}
